// Code generated by "stringer -type Error"; DO NOT EDIT.

package main

import "fmt"

const _Error_name = "ErrNoSuchResourceErrResourceExhausted"

var _Error_index = [...]uint8{0, 17, 37}

func (i Error) String() string {
	if i < 0 || i >= Error(len(_Error_index)-1) {
		return fmt.Sprintf("Error(%d)", i)
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
